import React from 'react';
import { Container, Typography, Box, Paper, Button, Divider, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, IconButton } from '@mui/material';
import { Add, Edit, Delete } from '@mui/icons-material';

const Allowance = () => {
  // Sample allowance data
  const allowanceData = [
    { id: 1, type: 'Housing Allowance', amount: 1000 },
    { id: 2, type: 'Transportation Allowance', amount: 500 },
    { id: 3, type: 'Medical Allowance', amount: 300 },
  ];

  const handleAddAllowance = () => {
    console.log('Add new allowance');
    // Functionality to add a new allowance
  };

  const handleEditAllowance = (id) => {
    console.log(`Edit allowance with id: ${id}`);
    // Functionality to edit an allowance
  };

  const handleDeleteAllowance = (id) => {
    console.log(`Delete allowance with id: ${id}`);
    // Functionality to delete an allowance
  };

  return (
    <Container maxWidth="lg">
      <Box sx={{ padding: 3 }}>
        <Paper elevation={3} sx={{ padding: 2 }}>
          {/* Header */}
          <Typography variant="h5" align="center" gutterBottom>
            Employee Allowance Breakdown
          </Typography>

          {/* Allowance Table */}
          <TableContainer component={Paper}>
            <Table>
              <TableHead>
                <TableRow>
                  <TableCell>Allowance Type</TableCell>
                  <TableCell align="right">Amount</TableCell>
                  <TableCell align="right">Actions</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {allowanceData.map((allowance) => (
                  <TableRow key={allowance.id}>
                    <TableCell component="th" scope="row">
                      {allowance.type}
                    </TableCell>
                    <TableCell align="right">${allowance.amount}</TableCell>
                    <TableCell align="right">
                      <IconButton onClick={() => handleEditAllowance(allowance.id)}>
                        <Edit />
                      </IconButton>
                      <IconButton onClick={() => handleDeleteAllowance(allowance.id)}>
                        <Delete />
                      </IconButton>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>

          {/* Add New Allowance Button */}
          <Box sx={{ textAlign: 'right', marginTop: 2 }}>
            <Button variant="contained" color="primary" onClick={handleAddAllowance} startIcon={<Add />}>
              Add New Allowance
            </Button>
          </Box>
          
          <Divider sx={{ margin: '20px 0' }} />
          
          {/* Footer Section */}
          <Box sx={{ textAlign: 'center' }}>
            <Typography variant="body2">Generated by Company KM digi commerce</Typography>
            <Typography variant="body2">For Internal Use Only</Typography>
          </Box>
        </Paper>
      </Box>
    </Container>
  );
};

export default Allowance;
