import React from 'react';
import { Container, Typography, Box, Paper, Button, IconButton, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Divider } from '@mui/material';
import { Add, Edit, Delete } from '@mui/icons-material';

const Deduction = () => {
  // Sample deduction data
  const deductionData = [
    { id: 1, type: 'Tax Deduction', amount: 500 },
    { id: 2, type: 'Health Insurance', amount: 200 },
    { id: 3, type: 'Loan Repayment', amount: 300 },
  ];

  const handleAddDeduction = () => {
    console.log('Add new deduction');
    // Logic to add a new deduction
  };

  const handleEditDeduction = (id) => {
    console.log(`Edit deduction with id: ${id}`);
    // Logic to edit a deduction
  };

  const handleDeleteDeduction = (id) => {
    console.log(`Delete deduction with id: ${id}`);
    // Logic to delete a deduction
  };

  return (
    <Container maxWidth="lg">
      <Box sx={{ padding: 3 }}>
        <Paper elevation={3} sx={{ padding: 2 }}>
          {/* Header */}
          <Typography variant="h5" align="center" gutterBottom>
            Employee Deduction Breakdown
          </Typography>

          {/* Deduction Table */}
          <TableContainer component={Paper}>
            <Table>
              <TableHead>
                <TableRow>
                  <TableCell>Deductions Type</TableCell>
                  <TableCell align="right">Amount</TableCell>
                  <TableCell align="right">Actions</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {deductionData.map((deduction) => (
                  <TableRow key={deduction.id}>
                    <TableCell component="th" scope="row">
                      {deduction.type}
                    </TableCell>
                    <TableCell align="right">${deduction.amount}</TableCell>
                    <TableCell align="right">
                      <IconButton onClick={() => handleEditDeduction(deduction.id)}>
                        <Edit />
                      </IconButton>
                      <IconButton onClick={() => handleDeleteDeduction(deduction.id)}>
                        <Delete />
                      </IconButton>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>

          {/* Add New Deduction Button */}
          <Box sx={{ textAlign: 'right', marginTop: 2 }}>
            <Button variant="contained" color="primary" onClick={handleAddDeduction} startIcon={<Add />}>
              Add New Deduction
            </Button>
          </Box>

          <Divider sx={{ margin: '20px 0' }} />

          {/* Footer Section */}
          <Box sx={{ textAlign: 'center' }}>
            <Typography variant="body2">Generated by Company KM digi commerce</Typography>
            <Typography variant="body2">For Internal Use Only</Typography>
          </Box>
        </Paper>
      </Box>
    </Container>
  );
};

export default Deduction;
