import React from 'react';
import { Container, Grid, Typography, Box, Divider, Paper } from '@mui/material';

const Payslip = () => {
  const employeeData = {
    name: 'John Doe',
    employeeId: 'EMP00123',
    department: 'Engineering',
    date: 'January 2025',
    position: 'Software Developer',
  };

  const salaryData = {
    basicSalary: 5000,
    housingAllowance: 1000,
    transportationAllowance: 500,
    deductions: 300,
    tax: 400,
  };

  const totalSalary =
    salaryData.basicSalary + salaryData.housingAllowance + salaryData.transportationAllowance - salaryData.deductions - salaryData.tax;

  return (
    <Container maxWidth="md">
      <Box sx={{ padding: 3 }}>
        <Paper elevation={3} sx={{ padding: 2 }}>
          <Typography variant="h5" align="center" gutterBottom>
            Payslip for {employeeData.name} - {employeeData.date}
          </Typography>

          <Grid container spacing={2}>
            {/* Employee Details Section */}
            <Grid item xs={12} md={6}>
              <Typography variant="h6">Employee Details</Typography>
              <Typography variant="body1">Name: {employeeData.name}</Typography>
              <Typography variant="body1">Employee ID: {employeeData.employeeId}</Typography>
              <Typography variant="body1">Department: {employeeData.department}</Typography>
              <Typography variant="body1">Position: {employeeData.position}</Typography>
            </Grid>

            {/* Salary Breakdown Section */}
            <Grid item xs={12} md={6}>
              <Typography variant="h6">Salary Breakdown</Typography>
              <Typography variant="body1">Basic Salary: ${salaryData.basicSalary}</Typography>
              <Typography variant="body1">Housing Allowance: ${salaryData.housingAllowance}</Typography>
              <Typography variant="body1">Transportation Allowance: ${salaryData.transportationAllowance}</Typography>
              <Typography variant="body1">Deductions: -${salaryData.deductions}</Typography>
              <Typography variant="body1">Tax: -${salaryData.tax}</Typography>
              <Divider sx={{ margin: '10px 0' }} />
              <Typography variant="h6">Total Salary: ${totalSalary}</Typography>
            </Grid>
          </Grid>

          <Divider sx={{ margin: '20px 0' }} />

          {/* Footer Section */}
          <Box sx={{ textAlign: 'center' }}>
            <Typography variant="body2">Generated by Company KM digi commerce</Typography>
            <Typography variant="body2">For Internal Use Only</Typography>
          </Box>
        </Paper>
      </Box>
    </Container>
  );
};

export default Payslip;
